# import = ["~/.config/sesh/other.toml"]

[default_session]
startup_command = "nvim +GoToFile"

[[session]]
name = "tmuxc"
path = "~/.config/tmux"
startup_command = "tmuxc && exit"

[[session]]
name = "nvimc"
path = "~/.config/nvim"
startup_command = "nvimc"

[[session]]
name = "zshc"
path = "~/.config/zsh"
startup_command = "zshc && exit"

[[session]]
name = "dotc"
path = "~/.config"
startup_command = "dotc"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua && exit"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml && exit"

[[session]]
name = "atuin config"
path = "~/.config/atuin"
startup_command = "nvim config.toml && exit"

[[session]]
name = "second brain 🧠"
path = "~"
startup_command = "nn && exit"

[[session]]
name = "my custom binaries"
path = "~/.config/bin"

[[session]]
name = "update nvim"
path = "/tmp"
startup_command = "brew upgrade neovim --fetch-HEAD && exit"

[[session]]
name = "update all"
path = "/tmp"
startup_command = "brew update && brew upgrade && exit"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

